version: "3.8"
services:
  front:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - back

  back:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/vendor
    ports:
      - "8000:8000"
    command: sh -c "composer install && php -S 0.0.0.0:8000 -t public"
    environment:
      DB_HOST: db
      DB_DATABASE: app
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - "8082:3000"

volumes:
  db_data:
